export const ADD_BREED = 'ADD_BREED';
export const DELETE_BREED = 'DELETE_BREED';
export const DELETE_ALL_BREEDS = 'DELETE_ALL_BREEDS';
export const RECEIVE_INITIAL_BREEDS = 'RECEIVE_INITIAL_BREEDS';
